### ISSUE TITLE
Thoughts on `Auto (a, s) (b, s) -> s -> Auto a b`

### ISSUE THREAD

**Issue by k0001** [mstksg/auto#4]
I'm not an expert with Arrows, so it might be the case that the tool I am going to propose isn't needed at all. Anyways, here I go. 

While trying to use “`proc` notation” to write an `Auto` I noticed that I couldn't have an “internal state” for the whole `proc` block as it can usually be done with `accum`, `mkState`, etc. So, I thought about how to have both and I came up with this:

``` haskell
evalState
  :: (MonadFix m, Serialize s)
  => Auto m (a, s) (b, s)
  -> s
  -> Auto m a b
evalState au0 = \s0 -> proc a -> do
    rec s <- delay s0 -< s'
        (b, s') <- au0 -< (a, s)
    arr id -< b
```

The idea is that, just like with `Control.Monad.State.state`, the state is passed around explicitely. And just like with `Control.Monad.State.evalState`, given an initial state you can hide/remove the `State` layer.

Here's an example using that tool in the REPL:

```
> streamAuto (evalState (arr (\(a,s) -> (a*s, s+1))) 0) [1,1,1,1]
[0,1,2,3]
```

Of course, that example is quite small, but you can imagine a `proc` block within which many arrows are interacting with each other, yet you want to carry some larger state spanning all of them. Consider this made-up example:

``` haskell
-- | `qux` has its internal state too!
qux :: Monad m => Auto m (Int, [Int]) (Int, [Int])
qux = proc (a, s) -> do
   b <- foo -< a
   if sum s >= 10
      then do
         c <- bar -< b
         arr id -< (10000 + c, [])
      else do
         arr id -< (b, a:s)

-- | Here we hide `qux`'s internal state!
qux' :: MonadFix m => Auto m Int Int
qux' = evalState qux []


-- These are not important, I just added them to simulate a “real world scenario” above.

foo :: Monad m => Auto m Int Int
foo = arr id

bar :: Monad m => Auto m Int Int
bar = arr id
```

Running `qux'` in the REPL:

```
> streamAuto Foo.qux' [1..20]
[1,2,3,4,10005,6,7,10008,9,10,10011,12,10013,14,10015,16,10017,18,10019,20]
```

Additionally, just as we can use `accum` when the internal state is the same as the `Auto` output, instead of using `mkState` with an internal state equal to the output value, we can introduce `evalAccum` as well, wich behaves just as `evalState` but without the redundancy between the state type and the output type:

``` haskell
evalAccum
  :: (MonadFix m, Serialize b)
  => Auto m (a, b) b
  -> b
  -> Auto m a b
evalAccum au0 = \b0 -> proc a -> do
    rec b <- delay b0 -< b'
        b' <- au0 -< (a, b)
    arr id -< b
```

In the REPL:

```
> streamAuto (evalAccum (arr (\(a,b) -> (a + b))) 0) [1..10]
[0,1,3,6,10,15,21,28,36,45]
```

My biggest ”issue” with this is the need for a `MonadFix` constraint, but maybe there's a way around it and I just havent figured it out.

What are your thoughts on this?

**Comment by mstksg** [comment]
Hi @k0001 

The main solution I've been working on for having a proc bloc with global state is by using `State` or `StateT` as the underlying monad, and by using `sealState` or `runStateA`.  I believe it can implement the idea you are thinking about.  In particular, `sealState` behaves in a similar way to your `evalState`.

An `Auto (State s) a b` can be considered an `Auto' a b`, where every composed `Auto` has access to a global mutable state of type `s` using the tools from `Control.Auto.Effects`  This lets you combine/write `proc` blocks with underlying state, and then "seal it off" (same as your `evalState`) at the end.

``` haskell
sealState :: Auto (StateT s m) a b -> s -> Auto m a b
runStateA :: Auto (StateT s m) a b -> s -> Auto m (a, s) (b, s)
```

For your example --

``` haskell
qux :: Auto (StateT [Int] m) Int Int
qux = proc a -> do
    b <- foo -< a
    s <- effect get -< ()
    if sum s >= 10
      then do
        c <- effect (put []) *> bar -< b
        id -< 10000 + c
      else do
        arrM (modify . (:)) -< a
        id -< b

qux' :: Monad m => Auto m Int Int
qux' = sealState qux []
```

Admittedly, the `qux` here is a bit more verbose, but it's a slightly contrived example.  I had a toy-ish usage on an [old blog post](http://blog.jle.im/entry/effectful-recursive-real-world-autos-intro-to-machine#in-state) exploring the ideas of `Auto` before the library was released (it's on a more primitive type, but the principles remain).

The main advantage for this is not with somthing like `qux` but with, like what you mentioned, blocks with many globally stateful arrows:

``` haskell
example :: Auto (StateT [Int] m) Int Int
example = proc x -> do
    y <- foo -< x
    z <- bar -< x + y
    arrM (modify . (:)) -< z+5
    a <- baz -< z * y
    t <- effect (drop 2) *> bar -< y
    foo . baz -< y+a*t
```

Where `foo`, `bar`, `baz`, etc., all interact with one underlying global state, and they all can work together.  And because "normal" `Auto`s that don't use global state are parameterized over all `m`, you can use them fine this way too.

In practice the main usage for an underlying `StateT` I've encountered is with random generation, using `System.Random` and modifying an underlying random seed that updates with every single thing that needs access to entropy.  In the end, you'd use `sealState` with the initial seed...and now you have a normal locally stateful `Auto` to compose with everything.  With this case however, it's a bit easier to use `MonadRandom`-package `Rand` monad and use `sealRandom` from `Control.Auto.Process.Random`.  I could imagine a situation like the global "cost" thing in the blog post I liked to, too.  These work pretty well with this model.

It also goes without saying that you should "seal" your global state as close as possible to the source and not leave it hanging around in places where you don't need it.  Needing global state is often an XY problem...but I trust that you have thought about other ways of approaching it without falling back to global state :)

**Comment by k0001** [comment]
@mstksg thanks for you response.

I'm afraid I completely missed the `Control.Auto.Effects` module! Of course `sealState` and friends are good solutions to this problem. Thank you.

Nevertheless, seeing as we have `runStateA :: Auto (StateT s m) a b -> Auto m (a, s) (b, s)`, it would probably be handy to have a function to go in the opposite direction too, so that its result can then be used with `sealState`: 

``` haskell
stateA :: Auto m (a, s) (b, s) -> Auto (StateT s m) a b
```

Then, `sealState . stateA` would have the exact same type as the `evalState` I mentioned before:

``` haskell
sealState . stateA  :: (Serialize s, Monad m) => Auto m (a, s) (b, s) -> s -> Auto m a b
```

If you think this is a good idea I can send you a pull reqest.

Thanks for your reply and for your excellent work on this library.

**Comment by mstksg** [comment]
Hm.  I see what's going on, but it's not really clear to me the benefit in choosing to write an `Auto m (a, s) (b, s)

**Comment by mstksg** [comment]
Hm...it's not immediately clear to me the benefits in working with an `Auto m (a, s) (b, s)` instead of an `Auto (StateT s m) a b` if you want to encode a self-modifying state loop.  I guess you can avoid going through the inner monad...but things like these are really what the inner monad are for.  Using the monad you can represent compositions and mergings using `Applicative`, `Category`, `Arrow`, etc. that would be messy to represent otherwise.  Using `Auto m (a, s) (b, s)` makes it tricky to compose, so its main benefit would be for one-off isolated use cases.  Going directly to `evalState` (using the naked constructors, not proc notation, like in `sealState` might be useful, actually...as in, your original idea.

I'm not really sure if it comes up often enough in real big-picture applications to be useful as API.  Admittedly the API is already pretty bloated, heh; I was going to trim some of it myself soon.  I'm also afraid that writing a lot of things like `Auto m (a, s) (b, s)` might lead to writing imperative-style code.  An `Auto m (a, s) (b, s)` is basically an imperative action...so such an `Auto` might benefit from a refactoring into a more declarative style.  If you see a situation that you think it is invaluable/leads to the best code big picture, please show me :)  I will re-asses.

A possibly unrelated thread, though --- Your `evalState` type signature _almost_ matches exactly the type signature of `loop` from `Control.Arrow`:

``` haskell
loop :: Monad m => Auto m (a, c) (b, c) -> Auto m a c
evalState :: Monad m => Auto m (a, c) (b, c) -> c -> Auto m a c
```

I wonder if there would be a neat way to express what you are doing in terms of `loop`.  Just thinking out loud here :)

I really do appreciate the suggestion and idea, so thanks :)  And if you can show me some good examples where this style gives expressive code, I'd be thrilled.

**Comment by k0001** [comment]
Justin,

Thanks for sharing your thoughts.

(I'm writing from the phone and it's late, please excuse any misspellings I
might introduce)

I should mention that I suggested 'stateA' just to complete the API. That
is, to me the API feels a bit incomplete if you can't "seal the state"
anymore after you've used 'runStateA', considering that all 'runStateA'
does is his give you an isomorphic representation of the auto with its
state exposed.

Considering that at times one has to compose his tools with others written
by other authors who might have opted for a different representation,
making it easy for users to compose these things anyway sounds like a good
idea to me.

Me, in the current experiment I'm doing I'll probably be using both
representations, as sometimes I find the code is easier to follow in one
representation,  and not so much in another. I think the 'evalAccum' I
mentioned before is a good example of a tool leading to cleaner code
compared to using the StateT explicitly.

And about 'loop': well, 'rec' in 'proc' notation is implemented in terms of
'loop', so that should explain it.

I have to go now, but let's continue talking about this.
Thank you.
Il 29/mar/2015 02:18 "Justin Le" notifications@github.com ha scritto:

**Comment by k0001** [comment]
I'll close this as #5 introduced the relevant changes already.
